
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
// import "./styles/bootstrap.min.css";
import "swiper/css";
import "aos/dist/aos.css";
import 'react-modal-video/scss/modal-video.scss';
import './assets/css/style.css';
import './assets/css/custom.css';
import './assets/css/style.min.css';
import '../styles/App.css'; 
import "./globals.css";
 import Header from "../partials/header/Header";
import Footer from "../components/FooterComponent/Footer";
import '@fortawesome/fontawesome-free/css/all.min.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Header />

        {/* Page content */}
        <main>{children}</main>

        {/* Footer is global */}
        <Footer />
      </body>
    </html>
  );
}
